image: node:latest

before_script:
    - chmod +x ci/install-browsers
    - ./ci/install-browsers

cache:
    paths:
        - node_modules/

test:
    script:
        - npm install
        - ./node_modules/@angular/cli/bin/ng test --browser=Chrome --single-run=true --watch=false

