image: node:latest

before-script:
    script:
        - chmod +x 777 ci/install-browsers
        - ci/install-browsers
        - npm install

cache:
    paths:
        - node_modules/

test:
    script:
        - xvfb-run -a ./node_modules/@angular/cli/bin/ng test --single-run=true --watch=false

