image: node:latest

before-script:
    script:
        # - chmod +x ci/install-browsers
        # - ./ci/install-browsers
        - npm install

cache:
    paths:
        - node_modules/

test:
    script:
        # - xvfb-run -a ./node_modules/@angular/cli/bin/ng test --browser PhantomJS --single-run=true --watch=false
        - ./node_modules/@angular/cli/bin/ng test --browser=PhantomJS --single-run=true --watch=false

