image: node:latest

#before_script:
#    script:
#        # - chmod +x ci/install-browsers
#        # - ./ci/install-browsers
#        - npm install

before_script:
#    - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"
#    - "echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\" > /etc/apt/sources.list.d/google.list"
#    - "apt-get update -yqqq"
#    - "apt-get install -y google-chrome-stable"
#    - "apt-get install -y xvfb"
    - npm install
#    - npm install -g gulp
#    - npm install semantic-ui --save
#    - gulp build sematic/


cache:
    paths:
        - node_modules/

test:
    script:
        - ./node_modules/@angular/cli/bin/ng test -c --single-run=true --watch=false --autoWatch=true

