image: node:latest

#before_script:
#    script:
#        # - chmod +x ci/install-browsers
#        # - ./ci/install-browsers
#        - npm install

before_script:
    - "chmod +x ci/install-browsers"
    - "./ci/install-browsers"
    - npm install -g gulp
    - npm install semantic-ui --save


cache:
    paths:
        - node_modules/

test:
    script:
        - npm install
        - ./node_modules/@angular/cli/bin/ng test --browser=PhantomJS --single-run=true --watch=false

