image: ubuntu

before-script:
    script:
        - apt-get update -y && apt-get upgrade -y
        - apt-get install -y nodejs
        - apt-get install -y npm
        - npm update npm -g
        - npm cache clean
        - npm install -g @angular/cli

test:
    script:
        - npm test
