image: node:latest

before-script:
    - ci/install-browsers
    - npm install

cache:
    paths:
        - node_modules/

test:
    script:
        - xvfb-run -a ./node_modules/@angular/cli/bin/ng test --single-run=true --watch=false

