image: node

stages:
    - test

cache:
    paths:
        - node_modules/

before-script:
    script:
        - npm install
        - npm update npm -g
        - npm cache verify
        - npm install -g @angular/cli

test:
    stage: test
    script:
        - npm test

