image: node:latest

#before_script:
#    script:
#        # - chmod +x ci/install-browsers
#        # - ./ci/install-browsers
#        - npm install

before_script:
    # make sure autoInstall is enabled.
    - "grep -q '\"autoInstall\": true' semantic.json"
    # make sure version is not specified.
    - "! grep -q '\"version\":' semantic.json"
    - npm install -g gulp
    - npm install semantic-ui --save


cache:
    paths:
        - node_modules/

test:
    script:
        - npm install
        - ./node_modules/@angular/cli/bin/ng test --browser=PhantomJS --single-run=true --watch=false

