sudo: required

services:
  - docker

env:
  - IMAGE_NAME=joebarrettukatc/observation-tool-client

script:
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  - provider: script
    edge: false
    script: docker push "$IMAGE_NAME":latest
    on:
      branch: master
  - provider: script
    edge: true
    script: docker push "$IMAGE_NAME":edge
    on:
      branch: development

